### PR TITLE
Update dependencies to allow Rails 6.1

### PR DESCRIPTION
**Pull request by geoffharcourt**
https://weblog.rubyonrails.org/2020/12/9/Rails-6-1-0-release/

It does not appear there's any upgrade concerns here, so we can expand
the allowed Rails versions to include 6.1.x.

### CODE REVIEW

**Comment by modosc** [comment]
i'll take a look at this tonight (or pr welcome :-)) - i'll need to add 6.1 to the testing suite/etc.

**Comment by geoffharcourt** [comment]
@modosc thank you for the quick review and merge! Can you cut a new version of the gem?

**Comment by modosc** [comment]
yup - waiting for ci to finish. i will get it it out today.

**Comment by modosc** [comment]
ok, 1.1.0 released: https://rubygems.org/gems/cloudflare-rails/versions/1.1.0

**Pull request merged**
