### PR TITLE
Add support for white listed ips

### PR DESCRIPTION
**Pull request by sebyx07**

### CODE REVIEW

**Comment by modosc** [comment]
thanks for the pr - can you explain what you're trying to solve here?

**Comment by sebyx07** [comment]
I have a case where I need to allow a known ip to be white listed along side cloudflare.

**Comment by swiknaba** [comment]
It would be nice to add such possibilities to the Readme 🙂.

**Comment by modosc** [comment]
is there a reason you can't use `config.action_dispatch.trusted_proxies` for this?

**Comment by modosc** [comment]
no response, closing. please reopen if you're still having issues.

**Pull request closed without merging**
