### PR TITLE
Follow redirects when looking up ip ranges

### PR DESCRIPTION
**Pull request by mpetrowi**
This change handles redirects when looking up IP ranges from Cloudflare.  This will
allow the code to function even if Cloudflare reorganizes their site.

This change also reverts the URLs back to the previous values without
trailing slashes since those are again listed by Cloudflare as the correct URLs. Currently
both addresses with and without trailing slashes resolve directly but I don't think we should
count on that in the future.

### CODE REVIEW

**Comment by mpetrowi** [comment]
I'm a little puzzled on those test failures.  I'm not seeing them locally.

**Comment by modosc** [comment]
thanks for the pr - i don't think i want to explicitly implement this behavior yet.

i'm concerned we'd accidentally end up in some sort of redirection loop and i'm hoping changes like this on cloudflare's side won't occur very frequently (i mean, it took almost a decade for this one to happen).

**Comment by mpetrowi** [comment]
In that case I would suggest at least reverting the URLS to the documented ones, without trailing slashes:

https://www.cloudflare.com/th-th/ips/

**Comment by modosc** [comment]
> In that case I would suggest at least reverting the URLS to the documented ones, without trailing slashes:
> 
> https://www.cloudflare.com/th-th/ips/

i'm hesitant to do that in case cloudflare makes the same breaking change that they made previously :/

**Pull request closed without merging**
