### PR TITLE
feat: added proxy server support

### PR DESCRIPTION
**Pull request by YouSysAdmin**
1. Added proxy server support
2. Added `open_timeout` parameter to Net::HTTP for resolving problems with timeout connection to a target host
3. Bump version to 2.4.1

### CODE REVIEW

**Comment by YouSysAdmin** [comment]
Related to #70 reported by @goofansu

**Comment by goofansu** [comment]
Hi @modosc, thank you for your suggestion, the problem is only certain kinds of requests need to go through proxy to bypass the firewall, while others don't. If the proxy is configured via ENV variables (`http_proxy` or `https_proxy`), most requests sent from HTTP client libraries will go through the proxy.

**Comment by modosc** [comment]
i see - another idea would be to add a `proxy_class` option which would take a [proxy class to use instead of Net::HTTP](https://ruby-doc.org/stdlib-3.0.1/libdoc/net/http/rdoc/Net/HTTP.html#method-c-Proxy). this way i only have to add a single config option and you'd be free to set it up however you wanted?

something like:
```
http_class = ::Rails.application.config.cloudflare.proxy_class || Net::HTTP
resp = http_class.start(uri.host,
                                   uri.port,
                                   use_ssl: true,
                                   read_timeout: ::Rails.application.config.cloudflare.timeout,
                                   open_timeout: ::Rails.application.config.cloudflare.timeout) do |http|
```
(i wish the proxy options were kwargs instead of positional, then this could be cleaner.  )

**Comment by goofansu** [comment]
Hi @modosc, according to [the doc](https://ruby-doc.org/stdlib-3.0.1/libdoc/net/http/rdoc/Net/HTTP.html#method-c-Proxy), the Proxy class is obsolete. It recommends to pass proxy params in the `new`, and also `start` because it internally calls `new`.

> This class is obsolete. You may pass these same parameters directly to [::new](https://ruby-doc.org/stdlib-3.0.1/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new). See [::new](https://ruby-doc.org/stdlib-3.0.1/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new) for details of the arguments.

So it seems this PR is OK except this line: https://github.com/modosc/cloudflare-rails/blob/751af66669e6bdae30435830375281f73e8917fb/lib/cloudflare/rails/railtie.rb#L60 because `http_proxy` is used by `Net::HTTP` automatically.

What do you think?

**Comment by modosc** [comment]
i'm going to close out this pr.

this behavior (supporting proxy only for certain requests) seems very specific to your usage and will introduce more complexity than i want to maintain.

**Comment by goofansu** [comment]
@modosc Ok, thank you, we are maintaining a fork for our use case.

**Pull request closed without merging**
